import mapboxgl from 'mapbox-gl/dist/mapbox-gl.js'

const {
  version,
  supported,
  setRTLTextPlugin,
  getRTLTextPluginStatus,
  Map,
  NavigationControl,
  GeolocateControl,
  AttributionControl,
  ScaleControl,
  FullscreenControl,
  Popup,
  Marker,
  Style,
  LngLat,
  LngLatBounds,
  Point,
  MercatorCoordinate,
  FreeCameraOptions,
  Evented,
  config,
  prewarm,
  clearPrewarmedResources,
  accessToken,
  baseApiUrl,
  workerCount,
  maxParallelImageRequests,
  clearStorage,
  workerUrl,
  workerClass,
  setNow,
  restoreNoww
} = mapboxgl;

export default mapboxgl;

export {
  version,
  supported,
  setRTLTextPlugin,
  getRTLTextPluginStatus,
  Map,
  NavigationControl,
  GeolocateControl,
  AttributionControl,
  ScaleControl,
  FullscreenControl,
  Popup,
  Marker,
  Style,
  LngLat,
  LngLatBounds,
  Point,
  MercatorCoordinate,
  FreeCameraOptions,
  Evented,
  config,
  prewarm,
  clearPrewarmedResources,
  accessToken,
  baseApiUrl,
  workerCount,
  maxParallelImageRequests,
  clearStorage,
  workerUrl,
  workerClass,
  setNow,
  restoreNoww
}
